.. |SHIELD:Code:Repository| image:: https://img.shields.io/badge/hdl-containers-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/containers GitHub repository'
   :height: 22
   :target: https://github.com/hdl/containers

.. |SHIELD:Code:License| image:: https://img.shields.io/github/license/hdl/containers?longCache=true&style=flat-square
   :alt: 'Code License'
   :height: 22
   :target: https://github.com/hdl/containers/blob/master/LICENSE

.. |SHIELD:Community:Chat| image:: https://img.shields.io/gitter/room/hdl/community.svg?longCache=true&style=flat-square&logo=gitter&logoColor=fff&color=4db797
   :alt: 'hdl/community on gitter.im'
   :height: 22
   :target: https://gitter.im/hdl/community

.. |SHIELD:HDL:packages| image:: https://img.shields.io/badge/hdl-packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/packages GitHub repository'
   :height: 22
   :target: https://github.com/hdl/packages

.. |SHIELD:HDL:awesome| image:: https://img.shields.io/badge/hdl-awesome-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/awesome GitHub repository'
   :height: 22
   :target: https://github.com/hdl/awesome

.. |SHIELD:HDL:constraints| image:: https://img.shields.io/badge/hdl-constraints-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/constraints GitHub repository'
   :height: 22
   :target: https://github.com/hdl/constraints

.. |SHIELD:HDL:smoke-tests| image:: https://img.shields.io/badge/hdl-smoke--tests-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/smoke-tests GitHub repository'
   :height: 22
   :target: https://github.com/hdl/smoke-tests

.. |SHIELD:Registry:GCR| image:: https://img.shields.io/badge/-gcr.io/hdl--containers-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'Google Container Registry'
   :height: 22
   :target: https://gcr.io/hdl-containers

.. |SHIELD:Registry:GHCR| image:: https://img.shields.io/badge/-ghcr.io/hdl-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'GitHub Container Registry'
   :height: 22
   :target: https://github.com/hdl/containers/packages

.. |SHIELD:Registry:Docker| image:: https://img.shields.io/badge/-docker.io/hdlc-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'Docker Hub'
   :height: 22
   :target: https://hub.docker.com/u/hdlc
