.. |SHIELD:Code:Repository| image:: https://img.shields.io/badge/hdl-containers-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/containers GitHub repository'
   :height: 22
   :target: https://github.com/hdl/containers

.. |SHIELD:Code:License| image:: https://img.shields.io/github/license/hdl/containers?longCache=true&style=flat-square&logo=Apache&label=Code
   :alt: 'Code License'
   :height: 22
   :target: License.html

.. |SHIELD:Documentation:License| image:: https://img.shields.io/badge/Doc-CC--BY%204.0-bf7600?longCache=true&style=flat-square&logo=CreativeCommons
   :alt: 'Documentation License'
   :height: 22
   :target: Doc-License.html

.. |SHIELD:Community:Chat| image:: https://img.shields.io/gitter/room/hdl/community.svg?longCache=true&style=flat-square&logo=gitter&logoColor=fff&color=4db797&label=Chat
   :alt: 'hdl/community on gitter.im'
   :height: 22
   :target: https://gitter.im/hdl/community

.. |SHIELD:Registry:GCR| image:: https://img.shields.io/badge/-gcr.io/hdl--containers-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'Google Container Registry'
   :height: 22
   :target: https://gcr.io/hdl-containers

.. |SHIELD:Registry:GHCR| image:: https://img.shields.io/badge/-ghcr.io/hdl-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'GitHub Container Registry'
   :height: 22
   :target: https://github.com/hdl/containers/packages

.. |SHIELD:Registry:Docker| image:: https://img.shields.io/badge/-docker.io/hdlc-555555.svg?longCache=true&style=flat-square&logo=OpenContainersInitiative&logoColor=f2f1ef
   :alt: 'Docker Hub'
   :height: 22
   :target: https://hub.docker.com/u/hdlc
