.. |SHIELD:Generic:GCR| image:: https://img.shields.io/badge/-gcr.io/hdl--containers/[ARCHITECTURE/][COLLECTION/]IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef
   :alt: Full image name (GCR)
   :height: 22

.. |SHIELD:Generic:GHCR| image:: https://img.shields.io/badge/-ghcr.io/hdl/[ARCHITECTURE/][COLLECTION/]IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: Full image name (GHCR)
   :height: 22

.. |SHIELD:Mirror:GCR:NoArchitecture| image:: https://img.shields.io/badge/-gcr.io/hdl--containers/COLLECTION/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef
   :height: 22

.. |SHIELD:Mirror:GHCR:NoArchitecture| image:: https://img.shields.io/badge/-ghcr.io/hdl/COLLECTION/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22

.. |SHIELD:Mirror:GCR:NoCollection| image:: https://img.shields.io/badge/-gcr.io/hdl--containers/ARCHITECTURE/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef
   :height: 22
   :target: https://gcr.io/hdl-containers

.. |SHIELD:Mirror:GHCR:NoCollection| image:: https://img.shields.io/badge/-ghcr.io/hdl/ARCHITECTURE/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22
   :target: https://github.com/hdl/containers/packages

.. |SHIELD:Mirror:Docker| image:: https://img.shields.io/badge/-docker.io/hdlc-555555.svg?longCache=true&style=flat-square&logo=Docker&logoColor=f2f1ef
   :height: 22
   :target: https://hub.docker.com/u/hdlc

.. |SHIELD:Mirror:GCR:Default| image:: https://img.shields.io/badge/-gcr.io/hdl--containers/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef
   :height: 22
   :target: https://gcr.io/hdl-containers

.. |SHIELD:Mirror:GHCR:Default| image:: https://img.shields.io/badge/-ghcr.io/hdl/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22
   :target: https://github.com/hdl/containers/packages
