.. |SHIELD:Generic:GHCR| image:: https://img.shields.io/badge/-ghcr.io/hdl/[ARCHITECTURE/][COLLECTION/]IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: Full image name (GHCR)
   :height: 22
   :target: https://github.com/hdl/containers/packages
   :class: shield

.. |SHIELD:Mirror:GHCR:NoArchitecture| image:: https://img.shields.io/badge/-ghcr.io/hdl/COLLECTION/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22
   :target: https://github.com/hdl/containers/packages
   :class: shield

.. |SHIELD:Mirror:GHCR:NoCollection| image:: https://img.shields.io/badge/-ghcr.io/hdl/ARCHITECTURE/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22
   :target: https://github.com/hdl/containers/packages
   :class: shield

.. |SHIELD:Mirror:Docker| image:: https://img.shields.io/badge/-docker.io/hdlc-555555.svg?longCache=true&style=flat-square&logo=Docker&logoColor=f2f1ef
   :height: 22
   :target: https://hub.docker.com/u/hdlc
   :class: shield

.. |SHIELD:Mirror:GHCR:Default| image:: https://img.shields.io/badge/-ghcr.io/hdl/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :height: 22
   :target: https://github.com/hdl/containers/packages
   :class: shield
