.. |SHIELD:HDL:conda-ci| image:: https://img.shields.io/badge/hdl-conda--ci-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/conda-ci GitHub repository'
   :height: 22
   :target: https://github.com/hdl/conda-ci

.. |SHIELD:HDL:conda-compilers| image:: https://img.shields.io/badge/hdl-conda--compilers-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/conda-compilers GitHub repository'
   :height: 22
   :target: https://github.com/hdl/conda-compilers

.. |SHIELD:HDL:conda-eda| image:: https://img.shields.io/badge/hdl-conda--eda-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/conda-eda GitHub repository'
   :height: 22
   :target: https://github.com/hdl/conda-eda

.. |SHIELD:HDL:conda-misc| image:: https://img.shields.io/badge/hdl-conda--misc-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/conda-misc GitHub repository'
   :height: 22
   :target: https://github.com/hdl/conda-misc

.. |SHIELD:HDL:conda-prog| image:: https://img.shields.io/badge/hdl-conda--prog-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/conda-prog GitHub repository'
   :height: 22
   :target: https://github.com/hdl/conda-prog
