.. |SHIELD:HDL:packages| image:: https://img.shields.io/badge/hdl-packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/packages GitHub repository'
   :height: 22
   :target: https://github.com/hdl/packages

.. |SHIELD:HDL:awesome| image:: https://img.shields.io/badge/hdl-awesome-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/awesome GitHub repository'
   :height: 22
   :target: https://github.com/hdl/awesome

.. |SHIELD:Site:awesome| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=hdl.github.io%2Fawesome&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fhdl.github.io%2Fawesome%2Findex.html
   :alt: 'hdl.github.io/awesome'
   :height: 22
   :target: https://hdl.github.io/awesome

.. |SHIELD:HDL:constraints| image:: https://img.shields.io/badge/hdl-constraints-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/constraints GitHub repository'
   :height: 22
   :target: https://github.com/hdl/constraints

.. |SHIELD:Documentation:constraints| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=hdl.github.io%2Fconstraints&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fhdl.github.io%2Fconstraints%2Findex.html
   :alt: 'hdl.github.io/constraints'
   :height: 22
   :target: https://hdl.github.io/constraints

.. |SHIELD:HDL:smoke-tests| image:: https://img.shields.io/badge/hdl-smoke--tests-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: 'hdl/smoke-tests GitHub repository'
   :height: 22
   :target: https://github.com/hdl/smoke-tests
