= HDL containers
:toc: left
:toclevels: 4
:repotree: https://github.com/hdl/containers/tree/master/
:toc-title: HDL containers
:icons: font

== Context

This project started in GitHub repository https://github.com/ghdl/ghdl[ghdl/ghdl] (which was named tgingold/ghdl back then). The main purpose was testing GHDL on multiple GNU/Linux distributions (Debian, Ubuntu and Fedora), since https://travis-ci.org/[Travis CI] supported Ubuntu only and Docker. For each target platform, two images were used, one for building and another one for testing.

Later, most of the Docker related sources were split to repository https://github.com/ghdl/docker[ghdl/docker]. There, some additional simulation tools were added, such as http://vunit.github.io/[VUnit] and http://gtkwave.sourceforge.net/[GtkWave]. Images including the https://github.com/ghdl/ghdl-language-server[ghdl-language-server] were also added. When synthesis features were added to GHDL, and since it provides a plugin for https://github.com/YosysHQ/yosys[Yosys], tools for providing a complete open source workflow were requested. Those were https://github.com/YosysHQ/nextpnr[nextpnr], https://github.com/YosysHQ/icestorm[icestorm], https://github.com/YosysHQ/prjtrellis[prjtrellis], https://github.com/YosysHQ/SymbiYosys[SymbiYosys], etc.

At some point, ghdl/docker had as much content related to non-GHDL tools, as resources related to the organisation. At the same time, https://symbiflow.github.io[SymbiFlow] aimed at gathering open source projects for providing an integrated open source EDA solution. However, it did not have official container images and https://symbiflow.github.io/developers.html[help was wanted]. This repository was intially created for moving all the tools which were not part of GHDL, from ghdl/docker to symbiflow/containers. However, apart from adding known Verilog tools, the scope was widened. Hence, the repository was published in https://github.com/hdl/containers[hdl/containers].

== Usage

Users can consume the ready-to-use images that include a single tool, or the ones including many of them.

_TBW_

== Contributing

This repository provides a set of base images for building and for runtime: link:{repotree}base.dockerfile[`base.dockerfile`]. All the images in the ecosystem are based on these:

* https://hub.docker.com/r/hdlc/build/tags[image:https://img.shields.io/docker/image-size/hdlc/build/base?longCache=true&style=flat-square&label=hdlc%2Fbuild:base&logo=Docker&logoColor=fff[title='hdlc/build:base Docker image size']] Debian Buster with updated `ca-certificates`, `curl` and Python 3.
* https://hub.docker.com/r/hdlc/build/tags[image:https://img.shields.io/docker/image-size/hdlc/build/build?longCache=true&style=flat-square&label=hdlc%2Fbuild:build&logo=Docker&logoColor=fff[title='hdlc/build:build Docker image size']] based on `base`, includes `clang` and `make`.
* https://hub.docker.com/r/hdlc/build/tags[image:https://img.shields.io/docker/image-size/hdlc/build/dev?longCache=true&style=flat-square&label=hdlc%2Fbuild:dev&logo=Docker&logoColor=fff[title='hdlc/build:dev Docker image size']] based on `build`, includes `cmake`, `libboost-all-dev` and `python3-dev`.

Then, for each project, a dockerfile and a GitHub Actions workflow are created. Those are used for:

* Tools are built using base images.
* Cache images based on `scratch` (and/or other reusable packages) are produced.
* Ready-to-use images based on the runtime base image are produced.
* Ready-to-use images are tested before uploading.

Depending on the tool, _package_ images are created too. Those are based on `scratch` and contain pre-built assets. Therefore, they are not really useful _per se_, but meant to be used for building other. In fact, multiple tools are merged into ready-to-use images for specific use cases.

Before working on adding or extending the support for a tool, please check the https://github.com/hdl/containers/issues[issues] and https://github.com/hdl/containers/pulls[pull requests], for avoiding duplicated effort in case anyone is already working on it. You can also join the chat at https://gitter.im/hdl/community[gitter.im/hdl/community].

NOTE: Currently, many projects don't use containers at all, hence, all images are generated in this repository. However, the workload is expected to be distributed between multiple projects in the ecosystem.

NOTE: At the moment, there is no triggering mechanism set up between different GitHub repositories. All the workflows in this repo are triggered by CRON jobs.

=== Graph

Understanding how all the pieces in this project fit together might be daunting for newcomers. Fortunately, there is a map for helping maintainers and contributors traveling through the ecosystem. Subdir link:{repotree}graph/[`graph/`] contains the source of a https://en.wikipedia.org/wiki/Directed_graph[directed graph], where the relations between workflows, dockerfiles, images and tests are shown.

(https://graphviz.org/[Graphviz])'s `digraph` format is used, hence, the graph can be rendered to multiple image formats. The SVG output is shown in xref:img-graph[xrefstyle=short]. Multiple colours and arrow types are used for describing different dependency types. All of those are explained in the legend: xref:img-legend[xrefstyle=short].

[#img-graph]
.Workflows, dockerfiles, images and tests.
[link=graph.svg]
image::graph.svg['Workflows, dockerfiles, images and tests', align='center']

[#img-legend]
.Legend of the directed graph.
[link=legend.svg]
image::legend.svg['Legend of the directed graph', align='center']

IMPORTANT: When contributing modifications to the workflows, the dockerfiles or the tests, it is of utmost importance to update the graph accordingly.

== References

* SymbiFlow:
** https://github.com/SymbiFlow/symbiflow-examples[SymbiFlow/symbiflow-examples]
** https://github.com/SymbiFlow/make-env[SymbiFlow/make-env]
*** http://bit.ly/edda-conda-eda-spec[bit.ly/edda-conda-eda-spec]: Conda based system for FPGA and ASIC Dev
*** https://github.com/SymbiFlow/make-env/issues/15[Support providing the environment using docker rather than conda #15]
* GHDL:
** https://github.com/ghdl/docker[ghdl/docker]
** https://github.com/ghdl/setup-ghdl-ci[ghdl/setup-ghdl-ci]
* DBHI:
** https://github.com/dbhi/qus[dbhi/qus]
** https://github.com/dbhi/docker[dbhi/docker]
* https://github.com/open-tool-forge/fpga-toolchain[open-tool-forge/fpga-toolchain]
* https://github.com/im-tomu/fomu-toolchain[im-tomu/fomu-toolchain]
* https://github.com/alpin3/ulx3s[alpin3/ulx3s]
* https://github.com/eine/elide/tree/master/elide/docker[eine/elide]
* https://github.com/hackfin/ghdl-cross.mk[hackfin/ghdl-cross.mk]
