== Collections and architectures

Images are organised in _collections_ and built for multiple architectures.
A _collection_ is a set of images which share a common ancestor; a base layer.
Having images with a common ancestor allows reducing bandwidth and disk usage when pulling several of them.
See https://docs.docker.com/storage/storagedriver/#images-and-layers[docs.docker.com: About storage drivers | Images and layers].


Collections:

* `debian/bullseye` based on `ARCHITECTURE/debian:bullseye-slim` (default)
* `debian/buster` based on `ARCHITECTURE/debian:buster-slim`
* `centos/7` based on `ARCHITECTURE/centos:7`

Architectures:

* https://hub.docker.com/u/amd64[amd64] (default)
* https://hub.docker.com/u/arm32v7[arm32v7]
* https://hub.docker.com/u/arm64v8[arm64v8]
* https://hub.docker.com/u/ppc64le[ppc64le]
* https://hub.docker.com/u/s390x[s390x]
* https://hub.docker.com/u/mips64le[mips64le]
* https://hub.docker.com/u/riscv64[riscv64]

Each image is published to image:https://img.shields.io/badge/-gcr.io/hdl--containers/&#91;ARCHITECTURE/&#93;&#91;COLLECTION/&#93;IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef[] and image:https://img.shields.io/badge/-ghcr.io/hdl/&#91;ARCHITECTURE/&#93;&#91;COLLECTION/&#93;IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[].

However, the `ARCHITECURE` and `COLLECTION` are optional because:

* Images for the default architecture are mirrored to image:https://img.shields.io/badge/-gcr.io/hdl--containers/COLLECTION/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef[] and image:https://img.shields.io/badge/-ghcr.io/hdl/COLLECTION/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[].
* Images of the default collection are mirrored to image:https://img.shields.io/badge/-gcr.io/hdl--containers/ARCHITECTURE/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef[] and image:https://img.shields.io/badge/-ghcr.io/hdl/ARCHITECTURE/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[].
* Images of the default collection for the default architecture are mirrored to https://hub.docker.com/u/hdlc[image:https://img.shields.io/badge/-docker.io/hdlc-555555.svg?longCache=true&style=flat-square&logo=Docker&logoColor=f2f1ef[title='Docker Hub']].
* Images of the default collection for the default architecture which are not `build` or `pkg` are mirrored to image:https://img.shields.io/badge/-gcr.io/hdl--containers/IMAGE-555555.svg?longCache=true&style=flat-square&logo=Google%20Cloud&logoColor=f2f1ef[] and image:https://img.shields.io/badge/-ghcr.io/hdl/IMAGE-555555.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[].

[IMPORTANT]
====
Image names and tags in this documentation are provided without the _registry prefix_.
Hence, one of the prefixes listed above needs to be used when actually pulling/using the images.
See link:ug/index.html[User Guide] for further details.
====

[IMPORTANT]
====
The table below shows the tools available in the default collection for the default architecture.
Some tools are available in a subset of collections or for a subset of architectures only.
Browse the registries and/or the Continuous Integration workflows for finding images available in collections other than
the default.
====

== Tools and images

By default, latest development versions (branches `master`|`main`) of tools are built.
Then, smoke tests are executed and, if successful, the corresponding images are updated in the registries.
However, some specific tools are _not_ built from sources, but installed through system package managers.
Those are marked with `!` in the table below.

[NOTE]
====
Package images are not to be used for executing the tools, but for composing images including multiple resources.
See link:dev/index.html#_package_images[Development: Package images] for further details.
====

include::tools.adoc[]

=== Images including multiple tools

* **S**imulation:
** OCIImage:sim[] GHDL + Verilator + Icarus Verilog
** OCIImage:sim/osvb[] cocotb, OSVVM and VUnit; on top of `sim`.
** OCIImage:sim/scipy-slim[] `matplotlib` and `numpy`, on top of `sim`.
** OCIImage:sim/scipy[] `osvb` on top of `scipy-slim`.
** OCIImage:sim/octave-slim[] `octave`, on top of `sim`.
** OCIImage:sim/octave[] `osvb` on top of `octave-slim`.
* **I**mplementation: GHDL + Yosys + nextpnr
** OCIImage:impl/ice40[] nextpnr-ice40 only, and OCIImage:impl/icestorm[] including icestorm.
** OCIImage:impl/ecp5[] nextpnr-ecp5 only, and OCIImage:impl/prjtrellis[] including prjtrellis.
** OCIImage:impl/generic[] nextpnr-generic only.
** OCIImage:impl/pnr[] all nextpnr targets (ecp5, ice40, and generic).
** OCIImage:impl[] impl:pnr, including icestorm and prjtrellis.
* **F**ormal:
** OCIImage:formal[] all solvers depending on Python 3.
** OCIImage:formal/min[] Z3 only.
** OCIImage:formal/all[] all solvers, depending on either Python 2 or Python 3.
* **P**rogramming: OCIImage:prog[]

=== SymbiFlow (Conda)

https://hdl.github.io/awesome/items/symbiflow/[SymbiFlow] is an ecosystem of EDA tools for the development of FPGAs of
multiple vendors.
The tools used in the SymbiFlow ecosystem are packaged by https://antmicro.com[Antmicro] and contributors using https://docs.conda.io/en/latest[Conda].
The sources of Conda packages for EDA tooling are found in
https://github.com/hdl/conda-ci[image:https://img.shields.io/badge/hdl-conda--ci-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/conda-ci GitHub repository']],
https://github.com/hdl/conda-compilers[image:https://img.shields.io/badge/hdl-conda--compilers-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/conda-compilers GitHub repository']],
https://github.com/hdl/conda-eda[image:https://img.shields.io/badge/hdl-conda--eda-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/conda-eda GitHub repository']],
https://github.com/hdl/conda-misc[image:https://img.shields.io/badge/hdl-conda--misc-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/conda-misc GitHub repository']] and
https://github.com/hdl/conda-prog[image:https://img.shields.io/badge/hdl-conda--prog-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/conda-prog GitHub repository']].

In HDL Containers, as a complement to container images based on tools built on other container images, a set of SymbiFlow is provided.
The base is OCIImage:conda[], which includes a https://docs.conda.io/en/latest/miniconda.html[Miniconda] setup.
On top of that, the following ready-to-use images allow following the guidelines in https://github.com/SymbiFlow/symbiflow-examples[image:https://img.shields.io/badge/SymbiFlow-symbiflow--examples-9258ff.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef&labelColor=5a2ab5[title='SymbiFlow/symbiflow-examples GitHub repository']]
(https://symbiflow-examples.rtfd.io/en/latest/building-examples.html[image:https://img.shields.io/website.svg?label=symbiflow-examples.rtfd.io&longCache=true&style=flat-square&url=http%3A%2F%2Fsymbiflow-examples.rtfd.io%2Fen%2Flatest%2Findex.html&logo=ReadTheDocs&logoColor=fff[title='symbiflow-examples.rtfd.io']]):

* OCIImage:symbiflow/xc7/toolchain[]: the toolchain for ``FPGA_FAM=xc7``, on top of ``conda``.
  The following images are based on this:
** OCIImage:symbiflow/xc7/a50t[]: includes architecture definitions for _xc7a50t_.
** OCIImage:symbiflow/xc7/a100t[]: includes architecture definitions for _xc7a100t_.
** OCIImage:symbiflow/xc7/a200t[]: includes architecture definitions for _xc7a200t_.
** OCIImage:symbiflow/xc7/z010[]: includes architecture definitions for _xc7z010_.
** OCIImage:symbiflow/xc7/z020[]: includes architecture definitions for _xc7z020_.
** OCIImage:symbiflow/xc7[]: includes all the architecture definitions for the _xc7_ family, except _xc7a200t_ (due to hard disk limits on GitHub Actions).
* OCIImage:symbiflow/eos-s3[]: the toolchain for ``FPGA_FAM=eos-s3`` and the architecture definitions, on top of ``conda``.

[IMPORTANT]
====
The compression ratio of these images is very high compared to other container images.
That is because these include a significant amount of data in text format, which is much better compressed than binaries.
As a result, the size of the images when pulled is approximately as follows:

* xc7/toolchain: 3 GB
* xc7/a50t: 6 GB
* xc7/a100t: 8.5 GB
* xc7/a200t: 15 GB
* xc7/z010: 5 GB
* xc7/z020: 7.5 GB
* xc7: 18 GB (would be 30 GB if a200t was included)
* eos-s3: 2 GB
====

== To Do

* https://github.com/khoapham/bitman[BitMan]
* https://hdl.github.io/awesome/items/ecpprog[ecpprog]
* https://hdl.github.io/awesome/items/fujprog[fujprog]
* https://hdl.github.io/awesome/items/netlistsvg[netlistsvg]
* https://github.com/StefanSchippers/xschem[xschem] (https://github.com/hdl/containers/issues/28[#28])
* http://opencircuitdesign.com/irsim/[IRSIM] (https://github.com/hdl/containers/issues/30[#30])
* https://github.com/adamgreig/ecpdap[ecpdap]
* https://github.com/lnis-uofu/LSOracle[LSOracle]

include::context.adoc[]

== References

* https://github.com/hadolint/hadolint[hadolint/hadolint]: Haskell Dockerfile Linter
* SymbiFlow:
** https://github.com/SymbiFlow/symbiflow-examples[SymbiFlow/symbiflow-examples]
** https://github.com/SymbiFlow/make-env[SymbiFlow/make-env]
*** http://bit.ly/edda-conda-eda-spec[bit.ly/edda-conda-eda-spec]: Conda based system for FPGA and ASIC Dev
*** https://github.com/SymbiFlow/make-env/issues/15[Support providing the environment using docker rather than conda #15]
* https://github.com/im-tomu/fomu-toolchain[im-tomu/fomu-toolchain]
* https://github.com/antmicro/runner[antmicro/runner]
* NixOS
** https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-dockerTools[nixos.org/manual: pkgs.dockerTools]
** https://nix.dev/tutorials/building-and-running-docker-images[nix.dev/tutorials: Building and running Docker images]
* LibreCores:
** https://github.com/librecores/ci-docker-image[librecores/ci-docker-image]
** https://github.com/librecores/docker-images[librecores/docker-images]
** LibreCores CI Infrastructure (LCCI):
*** https://github.com/lccitools[lccitools]
*** https://github.com/lccidocker[lccidocker]
* https://github.com/0x01be/rudder[0x01be/rudder]
* https://github.com/limerainne/Dockerize-EDA[limerainne/Dockerize-EDA]
* https://github.com/alpin3/ulx3s[alpin3/ulx3s]
* https://github.com/vmunoz82/eda_tools[vmunoz82/eda_tools]
* https://github.com/eine/elide/tree/master/elide/docker[eine/elide]
* https://github.com/cdsteinkuehler/QuartusBuildVMs[cdsteinkuehler/QuartusBuildVMs]
* https://github.com/ghdl/setup-ghdl-ci[ghdl/setup-ghdl-ci]
* https://github.com/hackfin/ghdl-cross.mk[hackfin/ghdl-cross.mk]

=== ASIC

* https://github.com/The-OpenROAD-Project[The-OpenROAD-Project]
* https://github.com/efabless/openlane[efabless/openlane]
* https://github.com/carlosedp/riscv-bringup[RISC-V bring-up tracker]
* https://docs.google.com/document/d/1hSLKsz9xcEJgAMmYYer5cDwvPqas9_JGRUAgEORx1Yw[A Step-by-Step Example: Layout of a CMOS Inverter Using SkyWater Technology (SKW) 130nm Process]

=== Google Container Regisry (GCR)

* https://github.com/salrashid123/gcr_stats[salrashid123/gcr_stats]
* https://github.com/gregsramblings/google-cloud-4-words[gregsramblings/google-cloud-4-words]: The Google Cloud Developer's Cheat Sheet

=== USB/IP

* https://github.com/gw0/docker-alpine-kernel-modules[gw0/docker-alpine-kernel-modules]
* https://github.com/virtualhere/docker[virtualhere/docker]
** https://www.virtualhere.com/windows_server_software[Windows USB Server]
** https://www.virtualhere.com/usb_client_software[USB Client]
** https://www.virtualhere.com/linux_console[Linux Console Client]
** https://www.virtualhere.com/client_api[Client API]
** https://hub.docker.com/r/virtualhere/virtualhere-client[hub.docker.com/r/virtualhere/virtualhere-client]
