== Context

This project started in GitHub repository https://github.com/ghdl/ghdl[ghdl/ghdl] (which was named tgingold/ghdl back
then).
The main purpose was testing GHDL on multiple GNU/Linux distributions (Debian, Ubuntu and Fedora), since https://travis-ci.org/[Travis CI] supported Ubuntu only and Docker.
For each target platform, two images were used, one for building and another one for testing.

Later, most of the Docker related sources were split to repository https://github.com/ghdl/docker[ghdl/docker].
There, some additional simulation tools were added, such as http://vunit.github.io/[VUnit] and http://gtkwave.sourceforge.net/[GtkWave].
Images including the https://github.com/ghdl/ghdl-language-server[ghdl-language-server] were also added.
When synthesis features were developed in GHDL, and since it provides a plugin for https://github.com/YosysHQ/yosys[Yosys],
tools for providing a complete open source bitstream generation and formal verification workflow were requested and
contributed.
Those were
https://github.com/YosysHQ/nextpnr[nextpnr],
https://github.com/YosysHQ/icestorm[icestorm],
https://github.com/YosysHQ/prjtrellis[prjtrellis],
https://github.com/YosysHQ/SymbiYosys[SymbiYosys],
etc.

At some point, ghdl/docker had as much content related to non-GHDL tools, as resources related to the organisation.
At the same time, https://symbiflow.github.io[SymbiFlow] aimed at gathering open source projects for providing an
integrated open source EDA solution.
However, it did not have official container images and https://symbiflow.github.io/developers.html[help was wanted].
This repository was initially created for moving all the tools which were not part of GHDL, from ghdl/docker to
symbiflow/containers.
However, apart from adding known Verilog tools, the scope was widened.
Hence, the repository was published in https://github.com/hdl/containers[hdl/containers].

In parallel to splitting ghdl/docker form ghdl/ghdl, https://github.com/dbhi/qus[dbhi/qus] was created as a
generalisation of https://github.com/multiarch/qemu-user-static[multiarch/qemu-user-static].
_qus_ was used in https://github.com/dbhi/containers[dbhi/containers] to build multi-architecture container images and
manifests on Continuous Integration (CI) services with amd64 hosts only (say Travis CI or https://github.com/features/actions[GitHub Actions]).
Currently, hdl/containers uses the same solution to build container images for _foreign_ architectures.
