# Authors:
#   Unai Martinez-Corral
#     <unai.martinezcorral@ehu.eus>
#
# Copyright Unai Martinez-Corral
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: .watch
run-name: '👀 ${{ inputs.message }}'

on:
  workflow_dispatch:
    inputs:
      schedule:
        description: 'JSON with pending dictionary, and inprogress and done lists.'
        required: true
        type: string
      rerun:
        description: 'Maximum number of attempts to run (failing) jobs.'
        required: false
        default: 3
        type: string
      message:
        description: 'Message to show in the name of the run.'
        required: false
        default: "dispatched"
        type: string

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}
  GH_INPUT_RERUN: ${{ inputs.rerun }}
  GH_INPUT_MESSAGE: ${{ inputs.message }}
  PYTHONUNBUFFERED: 1

jobs:

  watch:
    runs-on: ubuntu-latest
    outputs:
      schedule: ${{ steps.watch.outputs.schedule }}
    steps:
    - name: 🧰 Checkout
      uses: actions/checkout@v7
      # IMPORTANT:
      # If a Composite Action is used to wrap this script, the output is buffered/delayed!
      # See https://github.com/orgs/community/discussions/52284
    - name: 👀 Watch
      id: watch
      run: ./.github/watch.py
      env:
        GH_INPUT_SCHEDULE: ${{ inputs.schedule }}

  results:
    if: always()
    needs: watch
    runs-on: ubuntu-latest
    steps:
    - name: 🐍 Install Python dependencies
      run: pip3 install tabulate
    - name: 📊 Collect and process results
      uses: $/.github/self-script
      with:
        scriptfile: results.py
      env:
        GH_INPUT_SCHEDULE: ${{ needs.watch.outputs.schedule }}
        GH_WATCH_RESULT: ${{ needs.watch.result }}
