name: 'formal'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ formal ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  formal:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/formal:min formal min
    - run: dockerBuild hdlc/formal     formal latest
    - run: dockerBuild hdlc/formal:all formal

    - run: dockerTest  hdlc/formal:min formal--min
    - run: dockerTest  hdlc/formal     formal
    - run: dockerTest  hdlc/formal:all formal--all

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush  hdlc/formal:min
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/formal
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/formal:all
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
